In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[5,12,5]],columns=['cgpa','profile_score','lpa'])

In [3]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     5             12    5

In [29]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense,Input

In [30]:
model = Sequential()

model.add(Input(shape=(2,)))
model.add(Dense(2,activation='linear'))
model.add(Dense(1,activation='linear'))

In [31]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [32]:
model.get_weights()

[array([[-0.36758667,  0.16536152],
        [-0.5977791 ,  0.73078156]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.6053461],
        [1.0264393]], dtype=float32),
 array([0.], dtype=float32)]

In [33]:
new_weights = [np.array([[0.1,0.1],
                [0.1,0.1]],dtype=np.float32),
                np.array([0.,0.],dtype=np.float32),
                np.array([[0.1],
                [0.1]],dtype=np.float32),
                np.array([0.],dtype=np.float32)

               ]

In [34]:
model.set_weights(new_weights)

In [35]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [36]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 20.4140 
Epoch 2/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 17.1064
Epoch 3/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 19.9408
Epoch 4/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 16.7123
Epoch 5/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 18.4723
Epoch 6/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 16.3013
Epoch 7/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 18.1108
Epoch 8/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 15.8394
Epoch 9/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 15.6503
Epoch 10/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 15.3889
Epoch 11/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 17.0498
Epoch 12/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 14.9564
Epoch 13/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 14.7167
Epoch 14/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 17.2278
Epoch 15/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 17.0317
Epoch 16/75
3/3 ━━

In [39]:
model.get_weights()

[array([[0.3218521 , 0.3218521 ],
        [0.31817326, 0.31817326]], dtype=float32),
 array([0.22323073, 0.22323073], dtype=float32),
 array([[0.32400563],
        [0.32400563]], dtype=float32),
 array([0.17358717], dtype=float32)]