<a href="https://colab.research.google.com/github/TaraOnGit/ML_Agorithms_Coded_NBs/blob/master/MultipleLinearRegressionScratchVsSklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [16]:
from sklearn.metrics import mean_squared_error,r2_score

In [2]:
import numpy as np
import pandas as pd

In [13]:
X = pd.DataFrame(load_diabetes().data)
y = pd.DataFrame(load_diabetes().target)

In [20]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

# Multiple Linear Regression sklearn

In [17]:
mlr = LinearRegression()
mlr.fit(X_train,y_train)
y_pred = mlr.predict(X_test)
print('MSE ',mean_squared_error(y_test,y_pred))
print('R2 Score ',r2_score(y_test,y_pred))

MSE  2900.193628493482
R2 Score  0.4526027629719195


In [18]:
mlr.intercept_

array([151.34560454])

In [19]:
mlr.coef_

array([[  37.90402135, -241.96436231,  542.42875852,  347.70384391,
        -931.48884588,  518.06227698,  163.41998299,  275.31790158,
         736.1988589 ,   48.67065743]])

# Multiple Linear Regression From Scratch

In [29]:
class TaraMultipleLR:
  def __init__(self):
    self.intercept_ = None
    self.coef_ = None

  def fit(self,X_train,y_train):
    #inserting 1s as the first column of the coefs matrix for intercept
    X_train = np.insert(X_train,0,1,axis=1)

    # (XTX)-1.XTY
    betas_matrix = np.linalg.inv(np.dot((X_train.T),(X_train))).dot(X_train.T).dot(y_train)
    self.intercept_ = betas_matrix[0]
    self.coef_ = betas_matrix[1:]

  def predict(self,X_test):
    return np.dot(X_test,self.coef_) + self.intercept_

In [38]:
tmlr = TaraMultipleLR()
tmlr.fit(X_train,y_train)
y_pred1 = tmlr.predict(X_test)

# Comparing the MSE, R2_SCORE,intercept_ and coef_ values with that of sklearn's LR

In [37]:
print('MSE ',mean_squared_error(y_test,y_pred1))
print('R2 Score ',r2_score(y_test,y_pred1))

MSE  2900.193628493479
R2 Score  0.4526027629719199


In [31]:
tmlr.intercept_

array([151.34560454])

In [32]:
tmlr.coef_

array([[  37.90402135],
       [-241.96436231],
       [ 542.42875852],
       [ 347.70384391],
       [-931.48884588],
       [ 518.06227698],
       [ 163.41998299],
       [ 275.31790158],
       [ 736.1988589 ],
       [  48.67065743]])